include:
  - ../track-aw4ys.mongodb/docker-compose.yaml
  - ../track-aw4ys.kafka/docker-compose.yaml

services:
  simulator_prod:
    build:
      context: .
      target: final
      dockerfile: Dockerfile.prod
    container_name: simulator_prod
    environment:
      - MONGO_URI=mongodb://root:root@mongo:27017/routes?authSource=admin&directConnection=true
      - KAFKA_BROKER=kafka:9092
      - KAFKA_ROUTE_TOPIC=route
      - KAFKA_FREIGHT_TOPIC=freight
      - KAFKA_SIMULATION_TOPIC=simulation
      - KAFKA_GROUP_ID=route-group

  simulator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulator
    environment:
      - MONGO_URI=mongodb://root:root@mongo:27017/routes?authSource=admin&directConnection=true
      - KAFKA_BROKER=kafka:9092
      - KAFKA_ROUTE_TOPIC=route
      - KAFKA_FREIGHT_TOPIC=freight
      - KAFKA_SIMULATION_TOPIC=simulation
      - KAFKA_GROUP_ID=route-group
    depends_on:
      - mongo
      - kafka
    volumes:
      - .:/app
