include:
  - ../track-aw4ys.mongodb/docker-compose.yaml
  - ../track-aw4ys.kafka/docker-compose.yaml

services:
  nest:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
